### PR TITLE
Fixed: Cannot update attributes if a task contain at least one number attribute 

### LINKED ISSUE #2968: Cannot update attributes if a task contain at least one number attribute
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Can update attributes if a task contains number attributes

### Current Behaviour
Cannot update attributes if a task contain at least one number attribute

### Possible Solution
This is a bug. Need to fix.

### Steps to Reproduce (for bugs)

1. Create a task with a number attribute
1. Go to the corresponding label and try to change attributes/add new ones
1.
1.

Screenshot from 2021-03-17 17-47-03

### Your Environment

- Git hash commit (`git log -1`): c58074ea1f
- Docker version `docker version` (e.g. Docker 17.0.05): N/A 
- Are you using Docker Swarm or Kubernetes? N/A
- Operating System and version (e.g. Linux, Windows, MacOS): N/A

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #2968

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
Hi, @dvkruchinin 

Could you please update a task with attributes editing? (I believe we have similar, but maybe they do not cover this case)

**Comment by dvkruchinin** [comment]
> Could you please update a task with attributes editing? (I believe we have similar, but maybe they do not cover this case)
Sure. I`ll check and prepare a PR.

**Comment by ActiveChooN** [comment]
LGTM. But i have one request not entirely relevant to this PR. Can you change alignment to the top from the center in attributes rows to avoid  displaced layout along with a validator message?

**Comment by bsekachev** [comment]
> LGTM. But i have one request not entirely relevant to this PR. Can you change alignment to the top from the center in attributes rows to avoid displaced layout along with a validator message?

Sure. Done.

**Pull request merged**
