### PR TITLE
Add test for content type header

### PR DESCRIPTION
**Pull request by Marishka17**
### Checklist

- [x] I submit my changes into the `develop` branch
~~- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~
~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
- [x] I have added tests to cover my changes
~~- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~
~~- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
~~- [ ] I have updated the license header for each file (see an example below)~~

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@Marishka17 , could we extend https://github.com/openvinotoolkit/cvat/tree/develop/tests/rest_api? I really don't want to touch old tests anymore if they are working.

**Review by nmanovic — DISMISSED** [review]
@Marishka17 , LGTM. I would rename test_data.py to test_tasks.py (or test_0010_tasks.py if we decide to keep numbers in the file name).

**Comment by nmanovic** [comment]
@kirill-sizov , please look and advise.

**Review by kirill-sizov — APPROVED** [review]
We try to avoid using hardcoded data (usernames, ids, etc.) in tests.
But even though this test assumes that tasks with ids 1, 5, 6 will never change `Content-Type` and that `user1` will always see them, **I think this is a reasonable limitation** because it is difficult to change this information (except for example by deleting a task).

For sure it's easy to avoid this limitation with creating another one JSON file `headers.json`, but I suggest to delay this idea till it will be really needed.

**Review by nmanovic — APPROVED** [review]
LGTM

**Pull request merged**
