### PR TITLE
fixed: Permission error occured when accessing the JobCommits #4434

### LINKED ISSUE #4434: Permission error occured when accessing the JobCommits
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

- Related : #4368

### Expected Behaviour

- returns the list of tracked changes for the job
### Current Behaviour

- permission error occured (except admin account)
```html
HTTP 403 Forbidden
Allow: GET, HEAD, OPTIONS
Content-Type: application/vnd.cvat+json
Vary: Accept

{
    "detail": "You do not have permission to perform this action."
}
```
### Possible Solution

- add additional 'key:value'(('commits', 'GET'): 'view:commits') to the get_scopes() method in JobPermission class like below. (apps.iam.permissions.py)
```python
    @staticmethod
    def get_scopes(request, view, obj):
        scope = {
            ('list', 'GET'): 'list', # TODO: need to add the method
            ('retrieve', 'GET'): 'view',
            ('partial_update', 'PATCH'): 'update',
            ('update', 'PUT'): 'update', # TODO: do we need the method?
            ('destroy', 'DELETE'): 'delete',
            ('annotations', 'GET'): 'view:annotations',
            ('annotations', 'PATCH'): 'update:annotations',
            ('annotations', 'DELETE'): 'delete:annotations',
            ('annotations', 'PUT'): 'update:annotations',
            ('data', 'GET'): 'view:data',
            ('issues', 'GET'): 'view',
            ('commits', 'GET'): 'view:commits'
        }.get((view.action, request.method))
```
- add additional rule variable(VIEW_COMMITS:="view:commits") to the utils.rego
```rego
VIEW_DATA := "view:data"
VIEW_COMMITS := "view:commits"  <<---
UPLOAD_DATA := "upload:data"
```

-  update permission rule to the jobs.rego
```rego
allow {
    { utils.VIEW, utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_COMMITS }[input.scope]
    utils.is_sandbox
    is_job_staff
}

allow {
    { utils.VIEW, utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_COMMITS }[input.scope]
    input.auth.organization.id == input.resource.organization.id
    utils.has_perm(utils.USER)
    organizations.has_perm(organizations.MAINTAINER)
}

allow {
    { utils.VIEW, utils.VIEW_ANNOTATIONS, utils.VIEW_DATA, utils.VIEW_COMMITS }[input.scope]
    input.auth.organization.id == input.resource.organization.id
    organizations.has_perm(organizations.WORKER)
    is_job_staff
}
```

### Steps to Reproduce (for bugs)

1. create a task
1. open the job
1. create some shapes and save
1. access the /api/jobs/{id}/commits endpoint

### Your Environment

- Git hash commit (`git log -1`): b0e6074c
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by k1won**
### Motivation and context

Resolves #4434
### How has this been tested?

Manual test
### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@k1won , need to update the file https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/jobs.csv

**Comment by nmanovic** [comment]
Need to generate new tests: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/jobs_test.gen.rego. You can find the python script to generate it at the end of the file (as comments).

**Comment by k1won** [comment]
@nmanovic , I added the jobs.csv and jobs_test.gen.rego files that I modified a while ago.
And I ran opa test on my local dev environment and got the result as below.
```rego
$ opa test jobs_test.gen.rego jobs.rego utils.rego organizations.rego
PASS: 3300/3300
```

**Review by nmanovic — APPROVED** [review]
@k1won , great job! Thanks for all your time you invest into CVAT.

**Pull request merged**
