### PR TITLE
Fix AI Tools

### LINKED ISSUE #4432: AI tools Interactors no polygon output
Are the AI tool interactors disabled on the demo site? Having trouble using DEXTR specifically, after marking points no polygon is generated in any case. This issue is on the demo site and my install for me.

### PR DESCRIPTION
**Pull request by amteusch**
### Motivation and context
Pretty simple changes should fix #4432 

### How has this been tested?
Only tested by building locally, following instructions from [here](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/). DEXTR 
Screenshot from 2022-03-23 16-37-35
and YOLOv3 
Screenshot from 2022-03-23 16-36-58
worked but these are the only ones I tried. On Ubuntu 20.04.4. Please advise about tests and change log, I did not do either of these from the checklist but I'm not sure if they are needed for this small fix

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] ~~I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] ~~I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@amteusch , thanks for the contribution. We will add a test on our side. Could you please add a line to CHANGELOG.md?

**Comment by amteusch** [comment]
@nmanovic added the line but I think I didn't rebase properly... let me know what needs fixing

**Comment by nmanovic** [comment]
@amteusch , could you please merge our develop branch into your branch? You should have only 2 files in 'Files changed'.

**Comment by amteusch** [comment]
@nmanovic better?

**Review by nmanovic — APPROVED** [review]
@amteusch , thanks for the great contribution! We will add a test to avoid such issues in the future.

**Comment by nmanovic** [comment]
@ivk , could you please prepare a regression test for issue? Please work with @kirill-sizov to implement a way to test serverless functions.

**Comment by dprov** [comment]
I just installed cvat a few hours ago, and the fix does not seem to work. I still don't get a polygon, as in https://github.com/openvinotoolkit/cvat/issues/4432, both with DEXTR and HRnet.

FYI, I checked my cvat/apps/lambda_manager/views.py and it contains the fix in this PR.

**Pull request merged**
