### PR TITLE
CI. Using the Docker layer cache. Parallelizing test runs.

### PR DESCRIPTION
**Pull request by dvkruchinin**
### Motivation and context
Reducing the time of passing CI when a pull request or push is made to the default branch or master.
The logic of the work is based on creating a cache of the CVAT server build in the default branch and sharing the cache between other branches.
In a workflow named CI, the CVAT server is built from the cache (if it did not have any changes), tests are run, and coverage results are sent. Running e2e tests is organized as a division into 6 parallel jobs. During the verification phase, the CI pass rate was increased to 20 minutes.

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@dvkruchinin , I see that in several E2E_testing jobs in parallel we have "Rebuild CVAT step". Do we have a sequestional "build" step just before that?

**Comment by dvkruchinin** [comment]
@nmanovic 

> I see that in several E2E_testing jobs in parallel we have "Rebuild CVAT step". Do we have a sequestional "build" step just before that?

This implies using the cache created in the ```develop``` branch. If create a cache in each PR, this will lead to exceeding the cache size limit. 
As an option, I can change it to creating different cache in each PR, but the launch of the workflow when creating a PR will last about 40 minutes.

**Comment by dvkruchinin** [comment]
The coverage measurement will be triggered if the workflow trigger is generated from the develop branch.
Added caching of ```cvat_ui`` image in the develop branch. To speed up the build of the container in the pull request.
Added cache creation timeout. 7.5 minutes. If the cache creation workflow does not complete after this time, the image build will start from scratch. Creating a cache, provided that there is a cache from which a new one will be created, takes about 5-6 minutes. Waiting for the cache will significantly speed up the workflow process.
Cypress tests are divided into 10 directories.
Run for demonstration: https://github.com/dvkruchinin/cvat/actions/runs/788325066

**Review by nmanovic — APPROVED** [review]
LGTM

**Pull request merged**
