### PR TITLE
Better readme to Helm chart

### PR DESCRIPTION
**Pull request by kbegiedza**
### Motivation and context

Trying to install and configure with helm was very painful, this PR tries to cover few things:
* Better readme for first time users
* Init container with automatically invoked db migration

### How has this been tested?
Dry-run helm and released to brand new cluster.
Checked https certificates and frontend / backend connection.
image

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@kbegiedza , thanks for your contribution! @azhavoro , could you please look?

**Comment by azhavoro** [comment]
@kbegiedza Hello, what issue does the init container you added in this patch solve?

**Comment by kbegiedza** [comment]
@azhavoro Thanks for question.
It simplifies helm deployment by removing manual process (migration on first deployment).

Without it, I had to manually exec `manage.py migrate` inside pod, because database was empty.

**Comment by azhavoro** [comment]
> @azhavoro Thanks for question. It simplifies helm deployment by removing manual process (migration on first deployment).
> 
> Without it, I had to manually exec `manage.py migrate` inside pod, because database was empty.

The back-end container startup process invokes the migration on every run, including the first https://github.com/openvinotoolkit/cvat/blob/develop/supervisord.conf#L62 and I don't see the command is overridden in the deployment https://github.com/openvinotoolkit/cvat/blob/develop/helm-chart/templates/cvat_backend/deployment.yml#L44-L117 and it seems that this init container looks unnecessary. Your changes to README.md look ok, but I think it's better to understand why the migration is not run on first deployment in your case.

**Comment by kbegiedza** [comment]
Thanks for review @azhavoro, will remove init container from PR and investigate it further (and open new one if needed).

**Comment by kbegiedza** [comment]
@azhavoro fix'd

**Review by azhavoro — APPROVED** [review]

**Review by nmanovic — APPROVED** [review]
@kbegiedza , thanks for your contribution!

**Pull request merged**
