### PR TITLE
Cypress test. Collapse sidebar/apperance.

### PR DESCRIPTION
**Pull request by DmitriyOparin**
Cypress test. Collapse sidebar/apperance.
Add cssSelector for element.

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by DmitriyOparin** [comment]
This test will fail on new AntDesing version in branch upstream/bs/antd4_migration due to background does not  fitted when hide sidebar.

**Comment by dvkruchinin** [comment]
@DmitriyOparin Please recheck the test for the current develop branch.

**Comment by DmitriyOparin** [comment]
@bsekachev 
Test failed for the current develop branch due to background is not fitted when hide sidebar. 
Is bug or feature? Should remake test?

**Comment by bsekachev** [comment]
@DmitriyOparin 

Probably is is a bug, let me look into the issue.

**Comment by bsekachev** [comment]
Fixed in #2561

**Comment by DmitriyOparin** [comment]
Fine. I will recheck this test on bs/some_fixes branch and will talk results.

**Comment by DmitriyOparin** [comment]
Test is pass on bs/some_fixes branch. I will wait when fix will be in develop branch.

**Comment by DmitriyOparin** [comment]
Test is sucsess on develop branch.

**Review by ActiveChooN — APPROVED** [review]
LGTM

**Pull request merged**
