### PR TITLE
Fixed: Issues disappear when using a zoom

### LINKED ISSUE #3975: Issues disappear when using a zoom
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour

zoom1

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #3975 

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@ActiveChooN Could you please look at this patch?

**Comment by ActiveChooN** [comment]
Looks good, but is it possible to prevent moving lines from the issue pattern when the browser window is resizing?
issue-window-resize-issue1

**Comment by bsekachev** [comment]
> Looks good, but is it possible to prevent moving lines from the issue pattern when the browser window is resizing? issue-window-resize-issue1

I looked at API, tried some options and finally I am not sure we can control this effect. 
Taking into account the fact, that it is not a user scenario and it actually does not bring any issues for the user, let's keep as is.

**Comment by ActiveChooN** [comment]
> > Looks good, but is it possible to prevent moving lines from the issue pattern when the browser window is resizing? issue-window-resize-issue1
> 
> I looked at API, tried some options and finally I am not sure we can control this effect. Taking into account the fact, that it is not a user scenario and it actually does not bring any issues for the user, let's keep as is.

Sure.

**Review by ActiveChooN — APPROVED** [review]

**Comment by bsekachev** [comment]
Hi, @dvkruchinin Do you think we can test this case?

**Comment by dvkruchinin** [comment]
> Hi, @dvkruchinin Do you think we can test this case?

Hi @bsekachev,
I think it's possible. I'll try.

**Pull request merged**
