### PR TITLE
Cypress. Exclude some files from instrumentation.

### PR DESCRIPTION
**Pull request by dvkruchinin**
### Motivation and context
Increase code coverage by about 1%

File name | Comment
-- | --
/cvat-ui/src/actions/models-actions.ts | The code is not called in the standard CVAT build
/cvat-ui/src/actions/boundaries-actions.ts | If the application is running correctly, the code is not called.
/cvat-ui/src/containers/models-page/models-page.tsx | The code is not called in the standard CVAT build
/cvat-ui/src/reducers/models-reducer.ts | The code is not called in the standard CVAT build
/cvat-ui/src/utils/platform-checker.ts | Measure coverage conducted on a supported platform

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by ActiveChooN — APPROVED** [review]

**Comment by nmanovic** [comment]
@dvkruchinin , could we include testing of the page with models?

**Comment by dvkruchinin** [comment]
@nmanovic 
> could we include testing of the page with models?

Yes. I think it will be enough to change the CVAT build command in CI.

**Comment by nmanovic** [comment]
> @nmanovic
> 
> > could we include testing of the page with models?
> 
> Yes. I think it will be enough to change the CVAT build command in CI.

Let's do that in the case instead of excluding files from the coverage report.

**Comment by dvkruchinin** [comment]
> Let's do that in the case instead of excluding files from the coverage report.

Ok.
But I think it's worth keeping the files
```
/cvat-ui/src/actions/boundaries-actions.ts
/cvat-ui/src/utils/platform-checker.ts
```
Since they will not be covered

**Comment by nmanovic** [comment]
> > Let's do that in the case instead of excluding files from the coverage report.
> 
> Ok.
> But I think it's worth keeping the files
> 
> ```
> /cvat-ui/src/actions/boundaries-actions.ts
> /cvat-ui/src/utils/platform-checker.ts
> ```
> 
> Since they will not be covered

Agree

**Review by nmanovic — APPROVED** [review]

**Pull request merged**
