### PR TITLE
Replace Nginx proxy with Traefik

### LINKED ISSUE #3407: Replace Nginx with Traefik
Would you be interested in replacing Nginx proxy with [Traefik](https://doc.traefik.io/traefik/)?

Short pitch: Traefik can be a perfect substitute for Nginx, and unlike Nginx it is Docker-native. You can easily put all configuration inside the docker-compose file, and adding HTTPS/TLS is as easy as adding a few lines of configuration, no multi-step manual process is needed.

I have a perfectly functioning version of CVAT where I replaced Nginx with Traefik, and it runs great, without any issues. If you would be interesting in implementing Traefik here I can open a PR for it (and also tackle changing tests and updating documentation).

### PR DESCRIPTION
**Pull request by tadejsv**
### Motivation and context

This replaces the Nginx with a more "modern" proxy, Traefik.
There should be no change in the basic usage, i.e. the new `docker-compose.yml` file is a drop-in replacement for the old one. For using HTTPS the process becomes vastly simplified, and boils down to setting 2 env variables and using an override docker compose file.

Apart from HTTPS, the only other noticeable user-facing change is that the hostname is no longer set by the `CVAT_HOST` env variable in the proxy service, but by the `CVAT_HOST` env variable in the shell from which the user will execute the docker-compose command.

Closes #3407.

### How has this been tested?

I have tested the new `docker-compose.yml` file locally, and I have also tested the `docker-compose.https.yml` file on an EC2 instance with my own domain - HTTPS was properly set up, as expected. But it would be great if someone else would test this on their own, just to double-check.

Also, I am not sure how this would work with proxy (in [this sense](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#deploying-cvat-behind-a-proxy)). Should anyone be able to help me with checking this, that would be great.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by tadejsv** [comment]
@nmanovic This PR is now ready for review

**Comment by tadejsv** [comment]
@nmanovic Would you mind running the workflows here again?

**Review by azhavoro — CHANGES_REQUESTED** [review]
@tadejsv Hi,

Thanks for the contribution, great job!
I have 2 comments: 
- [ ] Could you please update the network section of https://github.com/openvinotoolkit/cvat/blob/develop/components/analytics/docker-compose.analytics.yml as well 
- [ ] Please fix conflicts and linter issues for changelog.md

**Comment by tadejsv** [comment]
Thanks for the feedback, @azhavoro . I have implemented the changes you suggested. If you re-run the workflows, I think all tests should pass

**Comment by nmanovic** [comment]
@tadejsv , great job! Thanks for the contribution.

**Review by nmanovic — DISMISSED** [review]

**Review by azhavoro — APPROVED** [review]

**Pull request merged**
