### PR TITLE
Cypress test. Filters features.

### PR DESCRIPTION
**Pull request by dvkruchinin**
### Motivation and context
Cypress test. Filters features.
I also slightly modified 2 tests in which elements are selected by label name on the labels tab. Made a selection using a regular expression.

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by ActiveChooN** [comment]
@dvkruchinin. Works fine, but test has slightly long duration about 250 seconds. Can we reduce it with creating task via API?

**Comment by dvkruchinin** [comment]
@ActiveChooN 
> test has slightly long duration about 250 seconds. Can we reduce it with creating task via API?

In CI, the annotation task already exists when the test is run. The test does not create it again, but only adds labels (In CI, the test time is about 50 seconds.). I also think it would be wrong to use the API in this tests since they are focused on testing the UI.
Alternatively, I can reduce the number of labels added and the number of objects created.

**Comment by ActiveChooN** [comment]
@dvkruchinin,

> I also think it would be wrong to use the API in this tests since they are focused on testing the UI.

Agree with you, can we use raw label editor in that case?

**Comment by dvkruchinin** [comment]
@ActiveChooN 
> can we use raw label editor in that case?

I think yes. Will check.

**Comment by dvkruchinin** [comment]
@ActiveChooN
 
> > can we use raw label editor in that case?
> 
> I think yes. Will check.

I checked this point. It turns out the same time, because Cypress is able to enter strings. Accordingly, it enters all json as a single string. I will reduce the number of added labels.

**Review by ActiveChooN — APPROVED** [review]
LGTM,
@bsekachev, can you please merge this PR?

**Pull request merged**
