### PR TITLE
Fixed of receiving 'function' variable

### LINKED ISSUE #2769: [Bug] UnboundLocalError at auto-annotations with empty data.
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
UnboundLocalError does not occurs. Response returned with status code = 400 Bad Requests.

### Current Behaviour
UnboundLocalError occurs. 

### Possible Solution
Fix the bug.

### Steps to Reproduce (for bugs)
1. Create task
2. Install function
3. Create POST query to '/api/v1/lambda/requests' with data = {} 

### Your Environment

- Git hash commit (`git log -1`): 3d4fad4c1b9ab4c79ae0636c82fe463a00c54e4d
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>

 </details>

>   File "/home/diman/.local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, args, *kwargs)
  File "/home/diman/git/cvat/cvat/apps/lambda_manager/views.py", line 499, in func_wrapper
    data = func(*args, **kwargs)
  File "/home/diman/git/cvat/cvat/apps/lambda_manager/views.py", line 594, in create
    '`{}` lambda function was run '.format(function) +
UnboundLocalError: local variable 'function' referenced before assignment

   

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by DmitriyOparin**
Fixed of receiving 'function' variable.
Resolve #2769 

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by DmitriyOparin** [comment]
@dvkruchinin, please review

**Comment by nmanovic** [comment]
@DmitriyOparin , could you please add a line into CHANGELOG.md (Fixed section)?

**Comment by dvkruchinin** [comment]
> @dvkruchinin, please review

LGTM. Also, please take the latest develop branch.

**Comment by DmitriyOparin** [comment]
> @DmitriyOparin , could you please add a line into CHANGELOG.md (Fixed section)?

Done

**Comment by DmitriyOparin** [comment]
> > @dvkruchinin, please review
> 
> LGTM. Also, please take the latest develop branch.

Done

**Review by nmanovic — APPROVED** [review]

**Pull request merged**
