### PR TITLE
IOG serverless function + some fixes 

### LINKED ISSUE #2227: Integrate Inside-Outside-Guidance semi-automatic segmentation
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible solution

Integrate the semi-automatic segmentation as a serverless function and write an article about the process.
https://github.com/shiyinzhang/Inside-Outside-Guidance

### LINKED ISSUE #2684: auto annotation tool Build path is directory - runtime must be specified
### My actions before raising this issue
- [√ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [√ ] Searched [past issues](/issues)

### Expected Behaviour
  nuctl deploy --project-name cvat \
    --path serverless/openvino/omz/public/yolo-v3-tf/nuclio \
    --volume `pwd`/serverless/openvino/common:/opt/nuclio/common \
    --platform local

### Current Behaviour
  nuctl deploy --project-name cvat \
    --path serverless/openvino/omz/public/yolo-v3-tf/nuclio \
    --volume `pwd`/serverless/openvino/common:/opt/nuclio/common \
    --platform local

Here is my error log：

root@Alex:~/Backend/components# nuctl deploy --project-name cvat --path serverless/openvino/omz/public/yolo-v3-tf/nuclio --volume `pwd`/serverless/openvino/common:/opt/n
uclio/common --platform local
21.01.20 13:06:00.792                     nuctl (I) Deploying function {"name": ""}
21.01.20 13:06:00.796                     nuctl (I) Building {"versionInfo": "Label: 1.5.8, Git commit: c12022750a6003a309d4f20c72a98addacd3e95d, OS: linux, Arch: amd64,
 Go version: go1.14.3", "name": ""}
21.01.20 13:06:00.807                     nuctl (W) Create function failed, setting function status {"err": "Failed create runtime", "errVerbose": "\nError - Build path
is directory - runtime must be specified\n    /nuclio/pkg/processor/build/builder.go:862\n\nCall stack:\nBuild path is directory - runtime must be specified\n    /nuclio
/pkg/processor/build/builder.go:862\nFailed create runtime\n    /nuclio/pkg/processor/build/builder.go:216\nFailed create runtime", "errCauses": [{"error": "Build path i
s directory - runtime must be specified", "errorVerbose": "\nError - Build path is directory - runtime must be specified\n    /nuclio/pkg/processor/build/builder.go:862\
n\nCall stack:\nBuild path is directory - runtime must be specified\n    /nuclio/pkg/processor/build/builder.go:862\nBuild path is directory - runtime must be specified"
, "errorCauses": [{}]}]}

Error - Build path is directory - runtime must be specified
    /nuclio/pkg/processor/build/builder.go:862

Call stack:
Build path is directory - runtime must be specified
    /nuclio/pkg/processor/build/builder.go:862
Failed create runtime
    /nuclio/pkg/processor/build/builder.go:216
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:175

### PR DESCRIPTION
**Pull request by nmanovic**
resolved #2227, resolved #2684,  

### Motivation and context

- Implemented [IOG](https://github.com/shiyinzhang/Inside-Outside-Guidance) serverless function for interactive segmentation. Now it isn't possible to draw a bounding box. Thus you have to add 2 negative points using 2 right clicks on the right mouse button (top left and bottom right corners of the bounding box) and a positive point in the middle of the object.

iog

- Updated nuclio version till 1.5.16
- All nuclio functions can be restarted after reboot (processor file is mounted as volume by nuclio `mountMode: volume`)
- Interactive functions support negative points now (right click on the mouse button)
- Refactored deploy_cpu.sh script (no code duplication anymore)
- Fixed serverless/tensorflow/matterport/mask_rcnn

### How has this been tested?

Manually deployed all functions and tested them.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@nmanovic 
On Ubuntu 20.04 I have default installed python 3.8.5 and it leads to the next installation issues:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - torchvision=0.2 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package _libgcc_mutex conflicts for:
python=3.8 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
pytorch=0.4 -> libgcc-ng[version='>=5.4.0'] -> _libgcc_mutex=[build=main]
```

The command I used: ``nuctl deploy --project-name cvat   --path serverless/pytorch/shiyinzhang/iog/nuclio/    --platform local
``

**Comment by bsekachev** [comment]
Also there are some issues found by codacy in Python & markdown code

**Comment by nmanovic** [comment]
@bsekachev , @azhavoro , could you please one more time? It looks like all problems were fixed.

**Comment by bsekachev** [comment]
Works, but sometime strange. 
Very depends on green point position

|         |            | 
| ------------- |:-------------:|
| Screenshot from 2021-02-10 16-59-01     |  Screenshot from 2021-02-10 17-00-05 |

**Review by bsekachev — APPROVED** [review]

**Comment by bsekachev** [comment]
I suppose some headers in the patch were updated incorrect: 2020 -> 2021 instead of 2020-2021. What's more I don't really understand why they updated in files without any other changes

**Comment by nmanovic** [comment]
> Works, but sometime strange.
> Very depends on green point position
> 
> Screenshot from 2021-02-10 16-59-01	Screenshot from 2021-02-10 17-00-05

from abstract for the article: Concretely, we leverage an inside point that is clicked near the object center and two outside points at the symmetrical corner locations (top-left and bottom-right or top-right and bottom-left) of a tight bounding box that encloses the target object.

**Comment by nmanovic** [comment]
> I suppose some headers in the patch were updated incorrect: 2020 -> 2021 instead of 2020-2021. What's more I don't really understand why they updated in files without any other changes

@azhavoro , could you please look at the issue?

**Pull request merged**
