### PR TITLE
fix build dependencies for Siammask

### PR DESCRIPTION
**Pull request by VRichardJP**
upstream SiamMask/requirements.txt is outdated and unmaintained

### Motivation and context

see https://github.com/openvinotoolkit/cvat/issues/4475

### How has this been tested?

The following commands could successfully build and deploy the network on my machine:
- `./serverless/deploy_cpu.sh serverless/pytorch/foolwood/siammask/nuclio`
- `./serverless/deploy_gpu.sh serverless/pytorch/foolwood/siammask/nuclio`

I could run the original SiamMask demo using the same changes: https://github.com/foolwood/SiamMask#demo

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@VRichardJP , thanks for the contribution. Is it ready for review?

**Comment by nmanovic** [comment]
@azhavoro , could you please test the PR?

**Comment by VRichardJP** [comment]
@nmanovic I think it is good to go

**Review by azhavoro — CHANGES_REQUESTED** [review]
@VRichardJP Hello, LGTM, but could you please add a note to the CHANGELOG.md?

**Review by azhavoro — APPROVED** [review]

**Review by nmanovic — APPROVED** [review]
@VRichardJP , thanks for the contribution!

**Pull request merged**
