### PR TITLE
Label form validator fix

### PR DESCRIPTION
**Pull request by ActiveChooN**
### Motivation and context

This PR fix label form validator to prevent creating labels with the same name.

### How has this been tested?

Manually.
@dvkruchinin, can you change test case 43 appropriate way to check form item validator additionally, please?

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
~~- [ ] I have added tests to cover my changes~~
~~- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by dvkruchinin** [comment]
@ActiveChooN 
> can you change test case 43 appropriate way to check form item validator additionally

Sure. I will prepare PR to this branch.

**Comment by bsekachev** [comment]
@vnishukov Please, review the PR

**Comment by dvkruchinin** [comment]
@ActiveChooN 
Is the correct behavior that after clicking on the Done button, the notification in the form of a pop-up window should now not appear?

**Review by vnishukov — APPROVED** [review]
Need to fix failed e2e tests

**Review by bsekachev — APPROVED** [review]

**Pull request merged**
