### PR TITLE
Cypress. Add test for check issue deleting feature.

### PR DESCRIPTION
**Pull request by dvkruchinin**
Related on #3952 
### Motivation and context
Modified case 28 to test functionality.

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Review by ActiveChooN — APPROVED** [review]

**Comment by ActiveChooN** [comment]
@dvkruchinin could you set the target branch as `nm/opa_integration`? these tests aren't needed in develop branch yet.

**Comment by dvkruchinin** [comment]
> @dvkruchinin could you set the target branch as `nm/opa_integration`? these tests aren't needed in develop branch yet.

@ActiveChooN  Changed the target and resolved conflicts.

**Review by ActiveChooN — APPROVED** [review]

**Comment by ActiveChooN** [comment]
@dvkruchinin, could you please look at linter problems?

**Comment by dvkruchinin** [comment]
> @dvkruchinin, could you please look at linter problems?

Temporarily disabled the corresponding ESLint rules.

**Comment by dvkruchinin** [comment]
I also saw that at the moment linter checks in CI are not working quite correctly. Not all files are taken into cheks. I am currently working on updating the corresponding workflow.

**Review by nmanovic — APPROVED** [review]

**Pull request merged**
