### PR TITLE
Added smooth image option

### PR DESCRIPTION
**Pull request by bsekachev**
Added switcher
image

**Smoothed:**
image

**Pixelized:**
image

### Motivation and context
Customer request

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
Hi, @nstolyarov 

This is PR regarding one of your requests. Will such the feature satisfy your needs?

**Comment by nstolyarov** [comment]
> Hi, @nstolyarov
> 
> This is PR regarding one of your requests. Will such the feature satisfy your needs?

Hi, @bsekachev 

Yes! This is exactly the feature that we need!

**Comment by bsekachev** [comment]
@ActiveChooN could you please review the patch?

**Review by nmanovic — APPROVED** [review]
LGTM, I didn't test the PR.

**Review by ActiveChooN — APPROVED** [review]

**Comment by bsekachev** [comment]
@TOsmanov @aschernov 

Hi, guys. Could you please look at this patch and update documentation accordingly?

**Comment by bsekachev** [comment]
Hi, @dvkruchinin 
Could you please write a test for this feature? Test is simple. When an option disabled, element ``cvat_canvas_background`` should have css property ``image-rendering`` set to ``crisp-edges`` or ``pixelated``

**Comment by TOsmanov** [comment]
> @TOsmanov @aschernov
> 
> Hi, guys. Could you please look at this patch and update documentation accordingly?

@bsekachev Hi. yes, sure

**Comment by dvkruchinin** [comment]
> Hi, @dvkruchinin Could you please write a test for this feature? Test is simple. When an option disabled, element `cvat_canvas_background` should have css property `image-rendering` set to `crisp-edges` or `pixelated`

Hi. Sure. A test will be prepared.

**Pull request merged**
