### PR TITLE
Added intelligent function when paste labels to another task

### LINKED ISSUE #919: Copying a “list of labels” from one task to another task
After last update, it is not possible to copy "label list" from one task to another.
An error occurred while copying "label list" from a raw view. Perhaps this is due to value "id" of each label.
Please make it possible to copy the “list of tags” from one task to another, this is necessary to create tasks with a similar or identical “list of labels”

### LINKED ISSUE #3717: Adjust "Copy labels" feature because it is not obvious now why a task cannot be created, after Ctrl+C, Ctrl+V existing labels from Raw editor
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I am trying to annotate a video on cvat of size 157mb. It was working for the past 1 month and I was annotating videos of size <500mb. But suddenly a week ago I got this error.
image
I tried after 2 days and today also and I was always getting the same error.
I even tried running cvat locally using docker but its giving me the same error.
Please help.

### Expected Behaviour

The task is successfully created.

### Current Behaviour

Error while creating the task.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Context

I am currently doing a project for school which requires annotating videos.
There aren't any free tools other than cvat which could help me achieve this task. So I started working with cvat for creating bounding boxes for YOLOv5 algorithm.

### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): Windows
- I am using the cvat website for creating the task

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by bsekachev**
Resolved #919
Resolved #3717

### Motivation and context
- [x] Added intelligent paste labels function (when user pasts a text, the function filters all the "id" fields.
- [x] Added confirmation when delete labels via Raw editor (it was implicitly before)
- [x] A bit adjusted behaviour of labels editor in general

Screenshot_37

 ### How has this been tested?
Manual testing

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@klakhov Could you please review the patch? Try to value the solution and find cases when it does not work

**Comment by bsekachev** [comment]
@nmanovic 

Maybe additionally to delete on the server label/attribute IDs when create a new task/project?
And when updating a task/project, to delete any unknown IDs?

**Comment by klakhov** [comment]
@bsekachev I've tried patch and it works as expected. No errors occur after labels copying.

Also I think its better to hide deleted labels/attributes paragraph if list is empty:
image

Btw why do we need to remove carriages if textarea does not contain them?
```
// remove all carriage characters (textarea value does not contain them)
replaced = replaced.replace(/\r/g, '');
```

**Comment by bsekachev** [comment]
@nmanovic 

I did the proposed changes above

**Comment by bsekachev** [comment]
@klakhov 

> Also I think its better to hide deleted labels/attributes paragraph if list is empty:

Sure, I did. 

> Btw why do we need to remove carriages if textarea does not contain them?

It is related with textarea properties selectionStart, selectionEnd. They don't consider ``\r`` characters (maybe it is a bug, I don't know). Also when we enter something manually it does not add ``\r`` characters to the field (and does not add it when we fill out the field from a labels specification). So, I've decided just to ignore all such characters from clipboardData because they can appear only from this place.

**Comment by nmanovic** [comment]
@bsekachev , I'm find with the PR. The only concern I have for now is about `update` operation and removing `id`. Could you please share your ideas why you think the implemented solution is right?

**Review by nmanovic — APPROVED** [review]
LGTM

**Comment by bsekachev** [comment]
@dvkruchinin

Could you please prepare a test with the following scenario:

1. From an existing task copy all labels and attributes (from the Row tab of the labels editor) (It must have at least one task and one attribute)
1. Go to the project create page, in the labels editor paste the copied text (ctrl + v)
1. Inserted JSON copy must not contain any "id": <N> fields
1. A project can be created with no errors

**Comment by dvkruchinin** [comment]
> @dvkruchinin
> 
> Could you please prepare a test with the following scenario:

@bsekachev 
Sure. A test will be prepared.

**Pull request merged**
