### PR TITLE
Dockercompose version update 2.3 --> 3.3

### LINKED ISSUE #2232: docker-compose file version update
Right now, CVAT is using docker-compose file version `2.3`. I have modified docker-compose file for version `3.3` with minor and non-intrusive changes. docker-compose file version3 changes can be seen [here](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3). I have chosen `3.3` because it support docker version `17.06.0+` like `2.3` which can be seen here at this [compatibility matrix](https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix). 

I am creating this issue to figure out if team has any specific reasons to stick to version `2.3`.

### PR DESCRIPTION
**Pull request by abdullahrkw**
### Motivation and Context
Resolves #2232 
I have removed the `gateway` key because it was not supported in dockercompose file [version3](https://github.com/docker/docker.github.io/pull/1636). But, if you specify subnet, docker automatically choose relevant [gateway](https://docs.docker.com/engine/reference/commandline/network_create/#specify-advanced-options). So, dockercompose network gateway is still `172.28.0.1`.
Moreover, I have added `driver` key with `default` value. docker-compose was already using default value.

### Checklist
- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] ~~I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
- [ ] ~~I have added tests to cover my changes~~
- [x] I have linked related issues 
- [ ] ~~I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] ~~I have updated the license header for each file (see an example below)~~

### CODE REVIEW

**Comment by bsekachev** [comment]
Hi,
One more file is: ``components/serverless/docker-compose.serverless.yml``

**Comment by bsekachev** [comment]
And looks like built is fault with these changes:

```
ERROR: The Compose file './docker-compose.ci.yml' is invalid because:

services.cvat_ci.build contains unsupported option: 'network'

The command "docker-compose -f docker-compose.yml -f docker-compose.ci.yml build" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by abdullahrkw** [comment]
> Hi,
> One more file is: `components/serverless/docker-compose.serverless.yml`

updated.

**Comment by bsekachev** [comment]
@azhavoro What do you think about this PR?

**Comment by abdullahrkw** [comment]
@bsekachev any update?

**Review by nmanovic — APPROVED** [review]
Thanks for the contribution! Looks good from my perspective.

**Comment by syedmohsinbukhari** [comment]
image

**Comment by dasmehdix** [comment]
Please update documentation about "share_path" for version "3.3" (also for new users). I can't mount my dataset into docker.

**Comment by bsekachev** [comment]
> Please update documentation about "share_path" for version "3.3" (also for new users). I can't mount my dataset into docker.

Did it work for 2.3, but doesn't work for 3.3?

**Comment by azhavoro** [comment]
> > Please update documentation about "share_path" for version "3.3" (also for new users). I can't mount my dataset into docker.
> 
> Did it work for 2.3, but doesn't work for 3.3?

I believe there is version mismatch here: https://github.com/openvinotoolkit/cvat/blame/develop/cvat/apps/documentation/installation.md#L329

**Comment by bsekachev** [comment]
I updated it in the PR #2261

**Pull request merged**
