### PR TITLE
Coninue from frame N, advanced user selector on jobs page

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
image
image

### How has this been tested?
Manual testing

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@klakhov 

Could you please review the patch?

**Review by klakhov — COMMENTED** [review]
@bsekachev Nice feature! Have you thought about adding a setting (a default-enabled checkbox for example) that can enable/disable 'continue from' notification, probably someone who don't need it would find it annoying.

**Comment by bsekachev** [comment]
> @bsekachev Nice feature! Have you thought about adding a setting (a default-enabled checkbox for example) that can enable/disable 'continue from' notification, probably someone who don't need it would find it annoying.

Let's wait for such reports.

**Comment by nmanovic** [comment]
@bsekachev , what I really like in notifications, it is easy way to disable them. But probably it is another feature. It should be done not only for the notification.

**Review by klakhov — APPROVED** [review]

**Comment by bsekachev** [comment]
@TOsmanov 

Could you please update documentation about continue working from frame N? 
Jobs page related documentation can be omitted for now, because it will be significantly updated soon/

**Pull request merged**
