### PR TITLE
Fix stage and state modification permission

### LINKED ISSUE #4323: Worker can finish a job without the required permissions
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The worker (annotator) can't finish a job with the "Finish the job" button, since that would skip the validation stage completely.

### Current Behaviour

The worker can press the "Finish the job" button, and the job is put into the acceptance stage and the completed stage. This skips the validation stage, and if this job is the only one in the task, then the task shows that it is completed. 

### Possible Solution

The stage and state modification permission should be implemented on the iam/opa side.

### Steps to Reproduce (for bugs)

1. Create an organization
2. Create a task in the organization
3. Assign the job to a worker
4. With the worker, open the job and press the "Finish the job" button on the annotation topbar

### Your Environment

- Git hash commit (`git log -1`): 237f98d5f834af3f752aa001ff95457701a311e5
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 20.10.11
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux
- Other diagnostic information / logs:
    - cvat_opa - doesn't log any incoming policy requests
    - cvat - doesn't show any errors

### PR DESCRIPTION
**Pull request by bseres99**
Closes #4323 

### Motivation and context

The state and stage of a job can be changed by anyone, without any permission checks, since the scopes haven't been passed to OPA, bypassing authorization.

### How has this been tested?

The change has been tested through a development environment set up on an ubuntu server. The changes were tested with the cvat UI through the use of the "Finish the job" button described in the connected issue, that can be found in the annotation topbar menu, when a job isn't in the "acceptance" stage and "completed" state. It has also been tested through api calls with users in all 4 groups in both sandbox and organization environments.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have fixed failing tests
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@bseres99 , thanks for the contribution! The fix looks right. Also please remove TODO: comments. It is already documented here: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/iam/rules/jobs.csv

**Comment by bseres99** [comment]
@nmanovic, of course, I will check off the items on the checklist as I am advancing with the PR. Once all checklist items are done, it will be ready for the merge. I will add the tests to the checklist!

**Comment by nmanovic** [comment]
@bseres99 , thanks. Please for old tests provide a `dummy` fix. Don't need to polish them.
If you are willing to add a new test, please follow the approach https://github.com/openvinotoolkit/cvat/pull/4295

**Comment by bseres99** [comment]
@nmanovic, should we update the CVAT backend version to 2.0.1? Or just write the changes to [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md), since 2.0.0 isn't officially released yet?

**Comment by nmanovic** [comment]
@bseres99 , CVAT is not released. Thus it is not necessary even mention the fix in CHANGELOG. Thanks for the great contribution! If CI is green, I will merge the PR.

**Review by nmanovic — APPROVED** [review]
LGTM

**Pull request merged**
