### PR TITLE
Label hotkeys

### PR DESCRIPTION
**Pull request by ActiveChooN**
### Motivation and context

Added hotkeys to change active object label or default label for drawing with numerical keys. Keys for labels could be changed via according buttons on control side bar panel in labels pane.

### How has this been tested?

Manually

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
~~- [ ] I have added tests to cover my changes~~
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@ActiveChooN 

Hmm.. What should we do with two PRs implementing the feature in a bit different way?

**Comment by bsekachev** [comment]
Tried this patch. Occasionally get error:
Screenshot from 2021-04-06 18-27-32

But I like this dropdown more:
Screenshot from 2021-04-06 18-30-52

What do you think if I move the dropdown to my version of patch and we will work on it?

**Comment by ActiveChooN** [comment]
> What do you think if I move the dropdown to my version of patch and we will work on it?
@bsekachev, sure. And i want to ask you keep old label item component style, because this style is applicable to object component due to it has normal height, but not to new version, because it is quite too contrast with small size of label item component.

**Comment by bsekachev** [comment]
@ActiveChooN 

I am not sure I understand you clearly, but style of label items was changed to be consistent with object.
Do you think we should not follow this way?

**Comment by ActiveChooN** [comment]
> takes too many space

@bsekachev , i'm agree with you, but i'm not sure about making all background colorful. Guess it can be better to make side color block and keep background color grey.

**Comment by bsekachev** [comment]
These changes moved to #3070

**Pull request closed without merging**
