### PR TITLE
removed listing of cloud storage bucket contents

### PR DESCRIPTION
**Pull request by shortcipher3**
Removed listing of cloud storage bucket contents.

### Motivation and context

When a cloud storage bucket contains a data lake it can take a long time to list the full contents resulting in errors in CVAT.  The contents are only listed to check whether the images in a task are available in the bucket.  It makes more sense to directly check for the images in the bucket. 

### How has this been tested?

Tested by loading a task with data stored on GCS.

### Checklist

- [x] I submit my changes into the `develop` branch

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by Marishka17** [comment]
@shortcipher3, Hi, Could you please leave changes only from `cache.py`? And in this case, I will approve this PR.

**Comment by shortcipher3** [comment]
> @shortcipher3, Hi, Could you please leave changes only from `cache.py`? And in this case, I will approve this PR.

done!

**Review by Marishka17 — APPROVED** [review]

**Comment by Marishka17** [comment]
Thanks for the contribution!

**Comment by Marishka17** [comment]
@dvkruchinin, Hi, Could you please take a look at the tests? `canvas3d_functionality_2` failed for some reason.

**Review by nmanovic — APPROVED** [review]

**Comment by nmanovic** [comment]
@shortcipher3 , thanks for the contribution!

**Pull request merged**
