### PR TITLE
Raw image copying in dataset export

### PR DESCRIPTION
**Pull request by zhiltsov-max**
### Motivation and context

Depends on https://github.com/openvinotoolkit/datumaro/pull/27

- Allows to copy raw images instead of recoding on dataset export
- Improves dataset export performance (4-6x +)

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

TBD: 
test on a large video with chunks and cache enabled, check `top` output
- memory leaking (extracted to https://github.com/openvinotoolkit/cvat/issues/2241). To reproduce:
```python
import gc
import tracemalloc
tracemalloc.start(10)
try:    
    from cvat.apps.engine.models import Task
    from cvat.apps.engine.frame_provider import FrameProvider
    fp = FrameProvider(Task.objects.get(pk=39).data) # a large video task

    while True:
        for i, f in enumerate(fp.get_frames(out_type=fp.Type.NUMPY_ARRAY)):
            pass

except:    
    del fp
    del f
    snapshot = tracemalloc.take_snapshot()    
    gc.collect()
```
- [x] very slow work (blame debugger?) - NO, blame Pillow and image conversion

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
@azhavoro, please take a look. To make it running, do 
`pip install 'git+https://github.com/openvinotoolkit/datumaro@zm/byteimage' --force-reinstall`

Please, also check #2241 on a large video task.

**Comment by azhavoro** [comment]
@zhiltsov-max there is something wrong with the image conversion:
frame_000000

**Comment by zhiltsov-max** [comment]
@azhavoro, fixed. The problem was that video frames are read as `yuv420p` (as encoded in chunks).

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please look at the problem?

```
f.handle(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 210, in build_graph
    self.load_disk()
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 112, in load_disk
    migration_module = import_module(migration_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/django/cvat/apps/engine/migrations/0017_db_redesign_20190221.py", line 7, in <module>
    from cvat.apps.dataset_manager.task import _merge_table_rows
  File "/home/django/cvat/apps/dataset_manager/task.py", line 18, in <module>
    from .bindings import TaskData
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 16, in <module>
    from datumaro.util.image import ByteImage, Image
ImportError: cannot import name 'ByteImage' from 'datumaro.util.image' (/usr/local/lib/python3.8/dist-packages/datumaro/util/image.py)
The command "docker-compose -f docker-compose.yml -f docker-compose.ci.yml run cvat_ci /bin/bash -c 'coverage run -a manage.py test cvat/apps && coverage run -a manage.py test --pattern="_test*.py" cvat/apps/dataset_manager/tests cvat/apps/engine/tests utils/cli && mv .coverage ${CONTAINER_COVERAGE_DATA_DIR}'" exited with 1.
```

**Review by azhavoro — APPROVED** [review]

**Pull request merged**
