### PR TITLE
Fixes server_files parsing to add them to a task using the API

### PR DESCRIPTION
**Pull request by mod-1**
### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by azhavoro** [comment]
@mod-1 Hi,
What bug will this patch fix?

**Comment by mod-1** [comment]
@azhavoro Hey, I was working with CVAT recently and wanted to add some data to a task using the API. The API documentation mentions that server_files should be in the following format: 
`server_files: [{files: '<file_path>'}]` 
The request is of type json and the server treats the dictionary as a string so it appends the file_path as follows: `BASEPATH/{files: '<file_path>'}`
The code above replaces all the single quotes with double quotes and the parses the string as a json and reads the file_path out of it thereby fixing the issue.

This is my first PR to an open-sourced project. So do bear with me and let me know if I need to do something a certain way. 
Thanks!

**Comment by mod-1** [comment]
image
 Seems like the API docs do not match the test cases written for the endpoint. Not sure what needs to be updated in this case

**Comment by azhavoro** [comment]
@mod-1 I think there is swagger documentation mismatch for this request, the request payload should have following structure:
```json
server_files[0]: 'relative path to the share file'
server_files[1]: 'relative path to the share file'
...
```

**Comment by mod-1** [comment]
@azhavoro Yeah I did realise that afterwards. Did some testing as well and it turns out that for the API the request format is as follows:
`
{
"image_quality": 100,
"server_files": ["relative path to the share file 1", "relative path to the share file 2"],
...
}
`

**Comment by azhavoro** [comment]
> @azhavoro Yeah I did realise that afterwards. Did some testing as well and it turns out that for the API the request format is as follows:
> `{ "image_quality": 100, "server_files": ["relative path to the share file 1", "relative path to the share file 2"], ... }`

Yes, this should work in case of Content-type: application/json and at the moment the swagger docs don't contain any notes about multipart/form-data which are also accepted by this endpoint, so in this case the request payload fields should be `server_files [ 0] ... `

**Comment by azhavoro** [comment]
@mod-1 So, lets close this PR, but you can help us to improve swagger documentation. Please let me know if you need any help.

**Pull request closed without merging**
