### PR TITLE
Fixed: cannot close some issues

### LINKED ISSUE #2607: Cannot close some issues
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

User should be able to close all issues on the frame

### Current Behaviour

If user creates few issues in one point, for example from context menu from one object, he can only close top one and other are not able for closing,

изображение

### Possible Solution

Restrict creating more than one issues from some object. Or bring selected in the right sidebar issue to the top layer on canvas.

### Steps to Reproduce (for bugs)

1. Open task and create some shape.
1. Go to the review mode
1. Create quick issue from the object
1. Create another issue from the same object
1. You have not be able to close first issue 

### Your Environment

- Git hash commit (`git log -1`): e6043671696816d199458ccf1ce94b54b37e909c
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.0
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #2607 

Added ability to scroll issues under cursor with mousewheel

### How has this been tested?
Manual testing

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@azhavoro 
Could you please assist me? What is wrong with Linter / ESLint build?
It just ends with status 1 without any error output. Locally check in precommit hook was fine

**Comment by azhavoro** [comment]
> @azhavoro
> Could you please assist me? What is wrong with Linter / ESLint build?
> It just ends with status 1 without any error output. Locally check in precommit hook was fine

image
@bsekachev there are some `unresolved path` errors, but I think it's false positive, we will try to investigate with Dmitry this issue. Maybe some configuration is missing.
I also agree, it would be nice to see errors in the logs in addition to the report.

**Comment by dvkruchinin** [comment]
@azhavoro 
eslint here is configured to write the report to an html file. In this case, there is no output in stdout. Alternatively, run eslint 2 times. With output to stdout and to an html file.
@bsekachev 
To solve the eslint error of the form I'm in PR #2867. I propose a solution in the form of an additional path in the path file ```.eslintrc```. This is because eslint in CI runs in the root project dir. And he doesn't know anything about the ```src``` folder.
https://github.com/openvinotoolkit/cvat/pull/2867/files#diff-4742993204a8e6ed2cb760fa609942a509c42c6baee85790275cb5461c0e34a2

**Comment by ActiveChooN** [comment]
Maybe it's better to add notification or disable button open issue for objects with opened one, what do you think?

**Comment by bsekachev** [comment]
> Maybe it's better to add notification or disable button open issue for objects with opened one, what do you think?

It does not prevent creating issue at the same position actually

**Review by ActiveChooN — APPROVED** [review]
LGTM

**Pull request merged**
