### PR TITLE
Z-Order flag in creation task process

### PR DESCRIPTION
**Pull request by vnishukov**
### Motivation and context
Bugfix for issue https://github.com/openvinotoolkit/cvat/issues/1390

### How has this been tested?
Create new task > Advanced options > Z-Order checkbox must be absent
Try to create a task. It should be created successfully

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by vnishukov** [comment]
Migration to db is in progress

**Comment by nmanovic** [comment]
@vnishukov , the only request from my side to start the review process is to separate refactoring and the actual changes. Is it possible?

**Comment by vnishukov** [comment]
> @vnishukov , the only request from my side to start the review process is to separate refactoring and the actual changes. Is it possible?

I will keep in mind this in future. Thanks!

**Comment by bsekachev** [comment]
@vnishukov 
Hi, how about minimizing code changes in the PR?

**Comment by vnishukov** [comment]
> @vnishukov
> Hi, how about minimizing code changes in the PR?

@bsekachev Done. Check it again, please

**Review by bsekachev — APPROVED** [review]

**Comment by bsekachev** [comment]
Great, thanks!

**Pull request merged**
