### PR TITLE
Fixed: "TypeError: Cannot read property 'clientX' of undefined"

### LINKED ISSUE #2873: The doubling of the cuboids to redraw.
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
When redrawing the cuboid, the number of shape does not increase.

### Current Behaviour
When redrawing the cuboid, the shape is doubled.

### Possible Solution
Fix the bug.

### Steps to Reproduce (for bugs)

1. Draw a cuboid.
2. Press Shift+N above it to start redrawing.
3. Redraw the cuboid.

### Your Environment

- Git hash commit (`git log -1`): 45a0530facf024e14a596c373babb38768069c28
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.2
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### LINKED ISSUE #3219: "TypeError: Cannot read property 'clientX' of undefined" error with redraw/repeat draw a cuboid.
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
A cuboid redraw/repeat draw successfully

### Current Behaviour
Getting an error:
```
svg.draw.js:270 Uncaught TypeError: Cannot read property 'clientX' of undefined
    at e.calc (svg.draw.js:270)
    at e.done (svg.draw.js:153)
    at t.draw (svg.draw.js:220)
    at t.a_.Element.draw (svg.patch.ts:29)
    at q_.release (drawHandler.ts:318)
    at q_.draw (drawHandler.ts:931)
    at dE.notify (canvasView.ts:1265)
    at t_.notify (master.ts:41)
    at t_.draw (canvasModel.ts:543)
    at hE.draw (canvas.ts:128)
```
canvas2d_2-issue

### Steps to Reproduce (for bugs)

1. Demonstrated above
At the time of redrawing/repeat drawing, press N or Shift+N.

### Your Environment

- Git hash commit (`git log -1`): ccb24c2a2cac92523893983738605a9f70ae9d42
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.5
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #3219
Resolved #2873 

### How has this been tested?
Manual testing

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by bsekachev** [comment]
@dvkruchinin 

Could you please update cypress tests with cuboids after PR is ready?

**Comment by dvkruchinin** [comment]
> Could you please update cypress tests with cuboids after PR is ready?

Sure. A tests will be updated.

**Comment by ActiveChooN** [comment]
@bsekachev, there is one case when the issue still appears. Steps to reproduce:
1. Draw a cuboid
2. Start redrawing with `Shift+N`
3. Try to finish redrawing with `N`

https://user-images.githubusercontent.com/8168727/122039007-e39bbb80-cdde-11eb-92db-68f7e28e9a0f.mp4

**Comment by bsekachev** [comment]
@ActiveChooN 
That was fixed.

**Review by ActiveChooN — APPROVED** [review]

**Pull request merged**
