### PR TITLE
Added validity check for polygon similarity computation related to issue #2851  

### LINKED ISSUE #2851: Export error when there are invalid polygons in the overlapping frames (shapely.errors.TopologicalError)
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Export of the datasets should go through without any issues.

### Current Behaviour

When there are invalid polygons in the overlapping frames, a notification pops out stating the export cannot be done, and an api call error stating: 
`
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed
`
Therefore blocking the export.

(in frames that have no overlapping, the invalid polygon does not block the export)

### Possible Solution

- ignore the invalid polygon when calculating similarity
- add validity check in the UI to prevent any creation of invalid polygon in the first place

### Steps to Reproduce (for bugs)

1. create a new task.
1. set the overlap size to an integer that is greater or equal to 1.
1. in the **overlapping** frames, draw an invalid polygon (self-overlapping polygon).
1. save and export the task.

### Context

We need the exported points' coordinates for further ML model training.

### Your Environment

- Operating System and version (e.g. Linux, Windows, MacOS): MacOS 11

### PR DESCRIPTION
**Pull request by fengyach**
Resolve #2851 

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@fengyach , could you please a line into CHANGELOG.md to reflex the fix?

**Comment by nmanovic** [comment]
@fengyach , please update the PR header as well. There are several checks:

image

**Comment by fengyach** [comment]
> @fengyach , could you please a line into CHANGELOG.md to reflex the fix?

thank you for your comment! I will update my PR!

**Comment by zhiltsov-max** [comment]
What do you think about this way of resolving the error? 
https://stackoverflow.com/a/20873812

**Comment by fengyach** [comment]
> What do you think about this way of resolving the error?
> https://stackoverflow.com/a/20873812

Hello!  Apologies for the late response:

Yes we have, however we do have a few concerns regarding self-intersecting multipolygons. As this method would not fix that issue. And we would have to figure out which polygon (whether it is p1 or p2) that is invalid.

**Review by zhiltsov-max — APPROVED** [review]

**Review by nmanovic — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
